import "@/styles/globals.css";

import { Inter } from "next/font/google";
import local from "next/font/local";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

const monaSans = local({
  src: [
    { path: "../fonts/Mona-Sans-Light.woff2", weight: "300" },
    { path: "../fonts/Mona-Sans-Regular.woff2", weight: "400" },
    { path: "../fonts/Mona-Sans-Medium.woff2", weight: "500" },
    { path: "../fonts/Mona-Sans-Bold.woff2", weight: "700" },
  ],
  variable: "--font-sans",
  fallback: ["Inter"],
});

const nohemi = local({
  src: [
    { path: "../fonts/Nohemi-Light.woff", weight: "300" },
    { path: "../fonts/Nohemi-Regular.woff", weight: "400" },
    { path: "../fonts/Nohemi-Medium.woff", weight: "500" },
    { path: "../fonts/Nohemi-Bold.woff", weight: "700" },
  ],
  variable: "--font-sans",
  fallback: ["Inter"],
});
console.log({ monaSans });

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${monaSans.variable}`}>{children}</body>
    </html>
  );
}
